### PR TITLE
Update to 1.02.

### PR DESCRIPTION
**Pull request by dwsteele**
- Remove static man page
- Remove fixed date from man generation.

I think it makes more sense to just use the current date during man generation.  Thoughts?

Also, I'm curious why you are including postgresql-common.  Is that just to get the postgresql user?

### CODE REVIEW

**Comment by disco-stu** [comment]
Thanks for the patch.

If we use the current date the package wouldn't be reproducible [1] but you're right using a static date is a bad idea. I would like to make sure the package will not differ between 2 builds based on the same tarball. I would like to use some file timestamp any idea which file we could use to generate the man page?

Yes the postgresql-common package is just for the postgres user. I'm uncertain about a pgbackrest user. IMHO in most cases one will use the postgres user to run the backup on a database machine itself were postgresql-common is already installed. I know this differs from scenarios where a dedicated backup host is involved but this setup needs some work anyway. Any Thoughts?

FYI: I will move the git repo to git.debian.org (pkg-postgresql namespace) at the latest when the package will be uploaded. This way Christoph could take care of it, if I'm not around.

[1] https://wiki.debian.org/ReproducibleBuilds

**Comment by dwsteele** [comment]
What if I write the date into a file in output/man?  Would that work for you?

I'm a bit nervous about requiring postgresql-common.  What happens if I have the apt.postgresql.org repo loaded and I require postgresql-common?  Isn't that going to pull from the Debian repo rather than apt.pg since there is no version specified?

**Comment by disco-stu** [comment]
If you put in the date the documentation was updated last it should work. I could grep the date from this file.

If postgresql-common is already installed it will keep the current version. If it's not installed it will fetch the highest package version (assumed all packages have the same apt priority).

**Comment by dwsteele** [comment]
OK, but we'll need to do that for the next release.  Just hardcode it for now and we'll fix it in 1.03.

I've tested the packages with PG installed from apt.pg.org and didn't see anything weird.  I might note in the docs that it's best to install PG first so there are no surprises.

**Pull request merged**
