### PR TITLE
Some changes to the package descriptions.

### PR DESCRIPTION
**Pull request by dwsteele**
Just a few changes to the wording based on work I'm doing on the main docs.

Also, I'd rather the default stanza was just "main".  I'm working on a feature that will allow version upgrades within a stanza.

### CODE REVIEW

**Comment by disco-stu** [comment]
Thanks. I applied a slightly modified patch. The package description consists of two parts short and long description. I kept the former short description and replace the long description. See be10474ce59f6eb6667ad9db1704d00590bba921.

**Comment by dwsteele** [comment]
Perfect, thanks!  I would say this is ready to go now, what's next?

**Comment by disco-stu** [comment]
I've already pushed the repository to git.debian.org [1]. Christoph will have a last look at the package and if he didn't find a show stopper he will upload the package to apt.d.o and Debian.

BTW: I will remove this repository in a few days to prevent confusion.

[1] http://anonscm.debian.org/cgit/pkg-postgresql/pgbackrest.git/

**Comment by dwsteele** [comment]
Awesome!  Will that also get to apt.postgresql.org?  It seems like that would be updated more frequently and releases generally come about once a month.

**Comment by disco-stu** [comment]
Sure. I have a typo in my former comment. I meant apt.postgresql.org not apt.d.o.

**Comment by dwsteele** [comment]
Excellent.  I really appreciate all your work and I think the package looks really good.

**Comment by disco-stu** [comment]
Thanks. But you're a very cooperative upstream author. That helped a lot ;).

**Comment by disco-stu** [comment]
FYI: The package was uploaded to apt.postgresql.org [1] and Debian. It's still in the NEW queue but should hit unstable in a few days.

[1] http://apt.postgresql.org/pub/repos/apt/pool/main/p/pgbackrest/

**Comment by dwsteele** [comment]
Can't wait!

**Pull request closed without merging**
